# Workloads

- Workload traces are a recording of the tasks executed on a system 

- Graph Greenifier requires two different traces:
    - **tasks.parquet** provides a general overview of the tasks executed during the workload.
    - **fragments.parquet** provides detailed information of each task during its runtime

In [1]:
import pandas as pd

df_tasks = pd.read_parquet("workload_traces/surf_month/tasks.parquet")
df_fragments = pd.read_parquet("workload_traces/surf_month/fragments.parquet")

## Workload Traces

- Traces define which tasks should be executed and when

- Provided as bag-of-task

- In this demo we run 1 month of Surfsara Lisa -> 68,648 tasks

In [2]:
df_tasks.head()

,id,submission_time,duration,cpu_count,cpu_capacity,mem_capacity,deferrable,deadline
0,1519830,1656604920000,1000,16,33600.0,97,True,1656691320000
1,1519833,1656604949000,1000,16,33600.0,97,True,1656691349000
2,1520988,1656605328000,315000,16,33600.0,97,True,1656691728000
3,1520994,1656605793000,330000,16,33600.0,97,True,1656692193000
4,1521049,1656608110000,248000,16,33600.0,97,True,1656694510000

### Fragments

<img src="./figures/fragments.jpg" width=600, alt="Alternative text" />

##### One month of Surfsara tasks has over 10 million fragments

In [3]:
df_fragments.head()

        id  duration  cpu_usage
0  1519830      1000    33600.0
1  1519833      1000    33600.0
2  1520988     12000        0.0
3  1520988     30000      420.0
4  1520988     30000      966.0

# Carbon Trace

Carbon Traces define the Carbon Intenisty of the available energy over time

Gathered using ENTSO-E

Specific to the location of the data center

Defined as a parquet file

In [4]:
df_carbon = pd.read_parquet("carbon_traces/NL_2021-2024.parquet")

df_carbon.head()

            timestamp  carbon_intensity
0 2021-01-01 00:00:00            464.62
1 2021-01-01 01:00:00            459.98
2 2021-01-01 02:00:00            454.93
3 2021-01-01 03:00:00            448.39
4 2021-01-01 04:00:00            455.50

# Experiment

- An Experiment defines what the Graph Greenifier should run, and how.

- Eperiments are defined using a JSON format

See the Experiment file [here](experiments/surfsara_month.json)

**Note:** Parameters are defined as lists, this makes it easy to run multiple experiments

# Running OpenDC

- OpenDC is executed directly from the terminal

- Only an experiment file is needed

In [28]:
import subprocess

pathToExperiment = "experiments/4.batteries/battery_experiment.json"
result = subprocess.run(["OpenDCExperimentRunner/bin/opendc", "run", pathToExperiment])

Starting replay

WARN
					Metrics after 24 hours:
						Tasks Total: 1172
						Tasks Active: 136
						Tasks Pending: 0
						Tasks Completed: 1036
						Tasks Terminated: 0

WARN
					Metrics after 24 hours:
						Tasks Total: 1172
						Tasks Active: 136
						Tasks Pending: 0
						Tasks Completed: 1036
						Tasks Terminated: 0

WARN
					Metrics after 24 hours:
						Tasks Total: 1172
						Tasks Active: 136
						Tasks Pending: 0
						Tasks Completed: 1036
						Tasks Terminated: 0

WARN
					Metrics after 48 hours:
						Tasks Total: 1413
						Tasks Active: 29
						Tasks Pending: 0
						Tasks Completed: 1384
						Tasks Terminated: 0

WARN
					Metrics after 48 hours:
						Tasks Total: 1413
						Tasks Active: 29
						Tasks Pending: 0
						Tasks Completed: 1384
						Tasks Terminated: 0

WARN
					Metrics after 48 hours:
						Tasks Total: 1413
						Tasks Active: 29
						Tasks Pending: 0
						Tasks Completed: 1384
						Tasks Terminated: 0

WARN
					Metrics after 72 hours:
						Tasks Total: 1608
						Tasks Active: 21
						Tasks Pending: 0
						Tasks Completed: 1587
						Tasks Terminated: 0

WARN
					Metrics after 72 hours:
						Tasks Total: 1608
						Tasks Active: 21
						Tasks Pending: 0
						Tasks Completed: 1587
						Tasks Terminated: 0

WARN
					Metrics after 72 hours:
						Tasks Total: 1608
						Tasks Active: 21
						Tasks Pending: 0
						Tasks Completed: 1587
						Tasks Terminated: 0

WARN
					Metrics after 96 hours:
						Tasks Total: 3087
						Tasks Active: 35
						Tasks Pending: 0
						Tasks Completed: 3052
						Tasks Terminated: 0

WARN
					Metrics after 96 hours:
						Tasks Total: 3087
						Tasks Active: 35
						Tasks Pending: 0
						Tasks Completed: 3052
						Tasks Terminated: 0

WARN
					Metrics after 96 hours:
						Tasks Total: 3087
						Tasks Active: 35
						Tasks Pending: 0
						Tasks Completed: 3052
						Tasks Terminated: 0

WARN
					Metrics after 120 hours:
						Tasks Total: 4613
						Tasks Active: 32
						Tasks Pending: 0
						Tasks Completed: 4581
						Tasks Terminated: 0

WARN
					Metrics after 120 hours:
						Tasks Total: 4613
						Tasks Active: 32
						Tasks Pending: 0
						Tasks Completed: 4581
						Tasks Terminated: 0

WARN
					Metrics after 120 hours:
						Tasks Total: 4613
						Tasks Active: 32
						Tasks Pending: 0
						Tasks Completed: 4581
						Tasks Terminated: 0

WARN
					Metrics after 144 hours:
						Tasks Total: 5491
						Tasks Active: 41
						Tasks Pending: 0
						Tasks Completed: 5450
						Tasks Terminated: 0

WARN
					Metrics after 144 hours:
						Tasks Total: 5491
						Tasks Active: 41
						Tasks Pending: 0
						Tasks Completed: 5450
						Tasks Terminated: 0

WARN
					Metrics after 144 hours:
						Tasks Total: 5491
						Tasks Active: 41
						Tasks Pending: 0
						Tasks Completed: 5450
						Tasks Terminated: 0

WARN
					Metrics after 168 hours:
						Tasks Total: 5969
						Tasks Active: 54
						Tasks Pending: 0
						Tasks Completed: 5915
						Tasks Terminated: 0

WARN
					Metrics after 168 hours:
						Tasks Total: 5969
						Tasks Active: 54
						Tasks Pending: 0
						Tasks Completed: 5915
						Tasks Terminated: 0

WARN
					Metrics after 168 hours:
						Tasks Total: 5969
						Tasks Active: 54
						Tasks Pending: 0
						Tasks Completed: 5915
						Tasks Terminated: 0

WARN
					Metrics after 192 hours:
						Tasks Total: 6794
						Tasks Active: 66
						Tasks Pending: 0
						Tasks Completed: 6728
						Tasks Terminated: 0

WARN
					Metrics after 192 hours:
						Tasks Total: 6794
						Tasks Active: 66
						Tasks Pending: 0
						Tasks Completed: 6728
						Tasks Terminated: 0

WARN
					Metrics after 192 hours:
						Tasks Total: 6794
						Tasks Active: 66
						Tasks Pending: 0
						Tasks Completed: 6728
						Tasks Terminated: 0

WARN
					Metrics after 216 hours:
						Tasks Total: 7314
						Tasks Active: 74
						Tasks Pending: 0
						Tasks Completed: 7240
						Tasks Terminated: 0

WARN
					Metrics after 216 hours:
						Tasks Total: 7314
						Tasks Active: 74
						Tasks Pending: 0
						Tasks Completed: 7240
						Tasks Terminated: 0

WARN
					Metrics after 216 hours:
						Tasks Total: 7314
						Tasks Active: 74
						Tasks Pending: 0
						Tasks Completed: 7240
						Tasks Terminated: 0

WARN
					Metrics after 240 hours:
						Tasks Total: 7977
						Tasks Active: 39
						Tasks Pending: 0
						Tasks Completed: 7938
						Tasks Terminated: 0

WARN
					Metrics after 240 hours:
						Tasks Total: 7977
						Tasks Active: 39
						Tasks Pending: 0
						Tasks Completed: 7938
						Tasks Terminated: 0

WARN
					Metrics after 240 hours:
						Tasks Total: 7977
						Tasks Active: 39
						Tasks Pending: 0
						Tasks Completed: 7938
						Tasks Terminated: 0

WARN
					Metrics after 264 hours:
						Tasks Total: 9618
						Tasks Active: 156
						Tasks Pending: 0
						Tasks Completed: 9462
						Tasks Terminated: 0

WARN
					Metrics after 264 hours:
						Tasks Total: 9618
						Tasks Active: 156
						Tasks Pending: 0
						Tasks Completed: 9462
						Tasks Terminated: 0

WARN
					Metrics after 264 hours:
						Tasks Total: 9618
						Tasks Active: 156
						Tasks Pending: 0
						Tasks Completed: 9462
						Tasks Terminated: 0

WARN
					Metrics after 288 hours:
						Tasks Total: 11069
						Tasks Active: 130
						Tasks Pending: 0
						Tasks Completed: 10939
						Tasks Terminated: 0

WARN
					Metrics after 288 hours:
						Tasks Total: 11069
						Tasks Active: 130
						Tasks Pending: 0
						Tasks Completed: 10939
						Tasks Terminated: 0

WARN
					Metrics after 288 hours:
						Tasks Total: 11069
						Tasks Active: 130
						Tasks Pending: 0
						Tasks Completed: 10939
						Tasks Terminated: 0

WARN
					Metrics after 312 hours:
						Tasks Total: 14997
						Tasks Active: 193
						Tasks Pending: 0
						Tasks Completed: 14804
						Tasks Terminated: 0

WARN
					Metrics after 312 hours:
						Tasks Total: 14997
						Tasks Active: 193
						Tasks Pending: 0
						Tasks Completed: 14804
						Tasks Terminated: 0

WARN
					Metrics after 312 hours:
						Tasks Total: 14997
						Tasks Active: 193
						Tasks Pending: 0
						Tasks Completed: 14804
						Tasks Terminated: 0

WARN
					Metrics after 336 hours:
						Tasks Total: 16752
						Tasks Active: 206
						Tasks Pending: 0
						Tasks Completed: 16546
						Tasks Terminated: 0

WARN
					Metrics after 336 hours:
						Tasks Total: 16752
						Tasks Active: 206
						Tasks Pending: 0
						Tasks Completed: 16546
						Tasks Terminated: 0

WARN
					Metrics after 336 hours:
						Tasks Total: 16752
						Tasks Active: 206
						Tasks Pending: 0
						Tasks Completed: 16546
						Tasks Terminated: 0

WARN
					Metrics after 360 hours:
						Tasks Total: 17933
						Tasks Active: 129
						Tasks Pending: 0
						Tasks Completed: 17804
						Tasks Terminated: 0

WARN
					Metrics after 360 hours:
						Tasks Total: 17933
						Tasks Active: 129
						Tasks Pending: 0
						Tasks Completed: 17804
						Tasks Terminated: 0

WARN
					Metrics after 360 hours:
						Tasks Total: 17933
						Tasks Active: 129
						Tasks Pending: 0
						Tasks Completed: 17804
						Tasks Terminated: 0

WARN
					Metrics after 384 hours:
						Tasks Total: 19072
						Tasks Active: 116
						Tasks Pending: 0
						Tasks Completed: 18956
						Tasks Terminated: 0

WARN
					Metrics after 384 hours:
						Tasks Total: 19072
						Tasks Active: 116
						Tasks Pending: 0
						Tasks Completed: 18956
						Tasks Terminated: 0

WARN
					Metrics after 384 hours:
						Tasks Total: 19072
						Tasks Active: 116
						Tasks Pending: 0
						Tasks Completed: 18956
						Tasks Terminated: 0

WARN
					Metrics after 408 hours:
						Tasks Total: 19427
						Tasks Active: 103
						Tasks Pending: 0
						Tasks Completed: 19324
						Tasks Terminated: 0

WARN
					Metrics after 408 hours:
						Tasks Total: 19427
						Tasks Active: 103
						Tasks Pending: 0
						Tasks Completed: 19324
						Tasks Terminated: 0

WARN
					Metrics after 408 hours:
						Tasks Total: 19427
						Tasks Active: 103
						Tasks Pending: 0
						Tasks Completed: 19324
						Tasks Terminated: 0

WARN
					Metrics after 432 hours:
						Tasks Total: 20937
						Tasks Active: 159
						Tasks Pending: 0
						Tasks Completed: 20778
						Tasks Terminated: 0

WARN
					Metrics after 432 hours:
						Tasks Total: 20937
						Tasks Active: 159
						Tasks Pending: 0
						Tasks Completed: 20778
						Tasks Terminated: 0

WARN
					Metrics after 432 hours:
						Tasks Total: 20937
						Tasks Active: 159
						Tasks Pending: 0
						Tasks Completed: 20778
						Tasks Terminated: 0

WARN
					Metrics after 456 hours:
						Tasks Total: 22387
						Tasks Active: 273
						Tasks Pending: 0
						Tasks Completed: 22114
						Tasks Terminated: 0

WARN
					Metrics after 456 hours:
						Tasks Total: 22387
						Tasks Active: 273
						Tasks Pending: 0
						Tasks Completed: 22114
						Tasks Terminated: 0

WARN
					Metrics after 456 hours:
						Tasks Total: 22387
						Tasks Active: 273
						Tasks Pending: 0
						Tasks Completed: 22114
						Tasks Terminated: 0

WARN
					Metrics after 480 hours:
						Tasks Total: 24301
						Tasks Active: 252
						Tasks Pending: 0
						Tasks Completed: 24049
						Tasks Terminated: 0

WARN
					Metrics after 480 hours:
						Tasks Total: 24301
						Tasks Active: 252
						Tasks Pending: 0
						Tasks Completed: 24049
						Tasks Terminated: 0

WARN
					Metrics after 480 hours:
						Tasks Total: 24301
						Tasks Active: 252
						Tasks Pending: 0
						Tasks Completed: 24049
						Tasks Terminated: 0

WARN
					Metrics after 504 hours:
						Tasks Total: 25880
						Tasks Active: 226
						Tasks Pending: 0
						Tasks Completed: 25654
						Tasks Terminated: 0

WARN
					Metrics after 504 hours:
						Tasks Total: 25880
						Tasks Active: 226
						Tasks Pending: 0
						Tasks Completed: 25654
						Tasks Terminated: 0

WARN
					Metrics after 504 hours:
						Tasks Total: 25880
						Tasks Active: 226
						Tasks Pending: 0
						Tasks Completed: 25654
						Tasks Terminated: 0

WARN
					Metrics after 528 hours:
						Tasks Total: 27270
						Tasks Active: 127
						Tasks Pending: 0
						Tasks Completed: 27143
						Tasks Terminated: 0

WARN
					Metrics after 528 hours:
						Tasks Total: 27270
						Tasks Active: 127
						Tasks Pending: 0
						Tasks Completed: 27143
						Tasks Terminated: 0

WARN
					Metrics after 528 hours:
						Tasks Total: 27270
						Tasks Active: 127
						Tasks Pending: 0
						Tasks Completed: 27143
						Tasks Terminated: 0

WARN
					Metrics after 552 hours:
						Tasks Total: 30122
						Tasks Active: 97
						Tasks Pending: 0
						Tasks Completed: 30025
						Tasks Terminated: 0

WARN
					Metrics after 552 hours:
						Tasks Total: 30122
						Tasks Active: 97
						Tasks Pending: 0
						Tasks Completed: 30025
						Tasks Terminated: 0

WARN
					Metrics after 552 hours:
						Tasks Total: 30122
						Tasks Active: 97
						Tasks Pending: 0
						Tasks Completed: 30025
						Tasks Terminated: 0

WARN
					Metrics after 576 hours:
						Tasks Total: 30674
						Tasks Active: 98
						Tasks Pending: 0
						Tasks Completed: 30576
						Tasks Terminated: 0

WARN
					Metrics after 576 hours:
						Tasks Total: 30674
						Tasks Active: 98
						Tasks Pending: 0
						Tasks Completed: 30576
						Tasks Terminated: 0

WARN
					Metrics after 576 hours:
						Tasks Total: 30674
						Tasks Active: 98
						Tasks Pending: 0
						Tasks Completed: 30576
						Tasks Terminated: 0

WARN
					Metrics after 600 hours:
						Tasks Total: 33314
						Tasks Active: 150
						Tasks Pending: 0
						Tasks Completed: 33164
						Tasks Terminated: 0

WARN
					Metrics after 600 hours:
						Tasks Total: 33314
						Tasks Active: 150
						Tasks Pending: 0
						Tasks Completed: 33164
						Tasks Terminated: 0

WARN
					Metrics after 600 hours:
						Tasks Total: 33314
						Tasks Active: 150
						Tasks Pending: 0
						Tasks Completed: 33164
						Tasks Terminated: 0

WARN
					Metrics after 624 hours:
						Tasks Total: 35894
						Tasks Active: 163
						Tasks Pending: 0
						Tasks Completed: 35731
						Tasks Terminated: 0

WARN
					Metrics after 624 hours:
						Tasks Total: 35894
						Tasks Active: 163
						Tasks Pending: 0
						Tasks Completed: 35731
						Tasks Terminated: 0

WARN
					Metrics after 624 hours:
						Tasks Total: 35894
						Tasks Active: 163
						Tasks Pending: 0
						Tasks Completed: 35731
						Tasks Terminated: 0

WARN
					Metrics after 648 hours:
						Tasks Total: 39943
						Tasks Active: 253
						Tasks Pending: 0
						Tasks Completed: 39690
						Tasks Terminated: 0

WARN
					Metrics after 648 hours:
						Tasks Total: 39943
						Tasks Active: 253
						Tasks Pending: 0
						Tasks Completed: 39690
						Tasks Terminated: 0

WARN
					Metrics after 648 hours:
						Tasks Total: 39943
						Tasks Active: 253
						Tasks Pending: 0
						Tasks Completed: 39690
						Tasks Terminated: 0

WARN
					Metrics after 672 hours:
						Tasks Total: 42909
						Tasks Active: 114
						Tasks Pending: 0
						Tasks Completed: 42795
						Tasks Terminated: 0

WARN
					Metrics after 672 hours:
						Tasks Total: 42909
						Tasks Active: 114
						Tasks Pending: 0
						Tasks Completed: 42795
						Tasks Terminated: 0

WARN
					Metrics after 672 hours:
						Tasks Total: 42909
						Tasks Active: 114
						Tasks Pending: 0
						Tasks Completed: 42795
						Tasks Terminated: 0

WARN
					Metrics after 696 hours:
						Tasks Total: 46868
						Tasks Active: 111
						Tasks Pending: 0
						Tasks Completed: 46757
						Tasks Terminated: 0

WARN
					Metrics after 696 hours:
						Tasks Total: 46868
						Tasks Active: 111
						Tasks Pending: 0
						Tasks Completed: 46757
						Tasks Terminated: 0

WARN
					Metrics after 696 hours:
						Tasks Total: 46868
						Tasks Active: 111
						Tasks Pending: 0
						Tasks Completed: 46757
						Tasks Terminated: 0

WARN
					Metrics after 720 hours:
						Tasks Total: 47022
						Tasks Active: 79
						Tasks Pending: 0
						Tasks Completed: 46943
						Tasks Terminated: 0

WARN
					Metrics after 720 hours:
						Tasks Total: 47022
						Tasks Active: 79
						Tasks Pending: 0
						Tasks Completed: 46943
						Tasks Terminated: 0

WARN
					Metrics after 720 hours:
						Tasks Total: 47022
						Tasks Active: 79
						Tasks Pending: 0
						Tasks Completed: 46943
						Tasks Terminated: 0

WARN
					Metrics after 744 hours:
						Tasks Total: 47117
						Tasks Active: 73
						Tasks Pending: 0
						Tasks Completed: 47044
						Tasks Terminated: 0

WARN
					Metrics after 744 hours:
						Tasks Total: 47117
						Tasks Active: 73
						Tasks Pending: 0
						Tasks Completed: 47044
						Tasks Terminated: 0

WARN
					Metrics after 744 hours:
						Tasks Total: 47117
						Tasks Active: 73
						Tasks Pending: 0
						Tasks Completed: 47044
						Tasks Terminated: 0

Starting replay

WARN
					Metrics after 24 hours:
						Tasks Total: 1172
						Tasks Active: 136
						Tasks Pending: 0
						Tasks Completed: 1036
						Tasks Terminated: 0

WARN
					Metrics after 24 hours:
						Tasks Total: 1172
						Tasks Active: 136
						Tasks Pending: 0
						Tasks Completed: 1036
						Tasks Terminated: 0

WARN
					Metrics after 24 hours:
						Tasks Total: 1172
						Tasks Active: 136
						Tasks Pending: 0
						Tasks Completed: 1036
						Tasks Terminated: 0

WARN
					Metrics after 48 hours:
						Tasks Total: 1413
						Tasks Active: 29
						Tasks Pending: 0
						Tasks Completed: 1384
						Tasks Terminated: 0

WARN
					Metrics after 48 hours:
						Tasks Total: 1413
						Tasks Active: 29
						Tasks Pending: 0
						Tasks Completed: 1384
						Tasks Terminated: 0

WARN
					Metrics after 48 hours:
						Tasks Total: 1413
						Tasks Active: 29
						Tasks Pending: 0
						Tasks Completed: 1384
						Tasks Terminated: 0

WARN
					Metrics after 72 hours:
						Tasks Total: 1608
						Tasks Active: 21
						Tasks Pending: 0
						Tasks Completed: 1587
						Tasks Terminated: 0

WARN
					Metrics after 72 hours:
						Tasks Total: 1608
						Tasks Active: 21
						Tasks Pending: 0
						Tasks Completed: 1587
						Tasks Terminated: 0

WARN
					Metrics after 72 hours:
						Tasks Total: 1608
						Tasks Active: 21
						Tasks Pending: 0
						Tasks Completed: 1587
						Tasks Terminated: 0

WARN
					Metrics after 96 hours:
						Tasks Total: 3087
						Tasks Active: 35
						Tasks Pending: 0
						Tasks Completed: 3052
						Tasks Terminated: 0

WARN
					Metrics after 96 hours:
						Tasks Total: 3087
						Tasks Active: 35
						Tasks Pending: 0
						Tasks Completed: 3052
						Tasks Terminated: 0

WARN
					Metrics after 96 hours:
						Tasks Total: 3087
						Tasks Active: 35
						Tasks Pending: 0
						Tasks Completed: 3052
						Tasks Terminated: 0

WARN
					Metrics after 120 hours:
						Tasks Total: 4613
						Tasks Active: 32
						Tasks Pending: 0
						Tasks Completed: 4581
						Tasks Terminated: 0

WARN
					Metrics after 120 hours:
						Tasks Total: 4613
						Tasks Active: 32
						Tasks Pending: 0
						Tasks Completed: 4581
						Tasks Terminated: 0

WARN
					Metrics after 120 hours:
						Tasks Total: 4613
						Tasks Active: 32
						Tasks Pending: 0
						Tasks Completed: 4581
						Tasks Terminated: 0

WARN
					Metrics after 144 hours:
						Tasks Total: 5491
						Tasks Active: 41
						Tasks Pending: 0
						Tasks Completed: 5450
						Tasks Terminated: 0

WARN
					Metrics after 144 hours:
						Tasks Total: 5491
						Tasks Active: 41
						Tasks Pending: 0
						Tasks Completed: 5450
						Tasks Terminated: 0

WARN
					Metrics after 144 hours:
						Tasks Total: 5491
						Tasks Active: 41
						Tasks Pending: 0
						Tasks Completed: 5450
						Tasks Terminated: 0

WARN
					Metrics after 168 hours:
						Tasks Total: 5969
						Tasks Active: 54
						Tasks Pending: 0
						Tasks Completed: 5915
						Tasks Terminated: 0

WARN
					Metrics after 168 hours:
						Tasks Total: 5969
						Tasks Active: 54
						Tasks Pending: 0
						Tasks Completed: 5915
						Tasks Terminated: 0

WARN
					Metrics after 168 hours:
						Tasks Total: 5969
						Tasks Active: 54
						Tasks Pending: 0
						Tasks Completed: 5915
						Tasks Terminated: 0

WARN
					Metrics after 192 hours:
						Tasks Total: 6794
						Tasks Active: 66
						Tasks Pending: 0
						Tasks Completed: 6728
						Tasks Terminated: 0

WARN
					Metrics after 192 hours:
						Tasks Total: 6794
						Tasks Active: 66
						Tasks Pending: 0
						Tasks Completed: 6728
						Tasks Terminated: 0

WARN
					Metrics after 192 hours:
						Tasks Total: 6794
						Tasks Active: 66
						Tasks Pending: 0
						Tasks Completed: 6728
						Tasks Terminated: 0

WARN
					Metrics after 216 hours:
						Tasks Total: 7314
						Tasks Active: 74
						Tasks Pending: 0
						Tasks Completed: 7240
						Tasks Terminated: 0

WARN
					Metrics after 216 hours:
						Tasks Total: 7314
						Tasks Active: 74
						Tasks Pending: 0
						Tasks Completed: 7240
						Tasks Terminated: 0

WARN
					Metrics after 216 hours:
						Tasks Total: 7314
						Tasks Active: 74
						Tasks Pending: 0
						Tasks Completed: 7240
						Tasks Terminated: 0

WARN
					Metrics after 240 hours:
						Tasks Total: 7977
						Tasks Active: 39
						Tasks Pending: 0
						Tasks Completed: 7938
						Tasks Terminated: 0

WARN
					Metrics after 240 hours:
						Tasks Total: 7977
						Tasks Active: 39
						Tasks Pending: 0
						Tasks Completed: 7938
						Tasks Terminated: 0

WARN
					Metrics after 240 hours:
						Tasks Total: 7977
						Tasks Active: 39
						Tasks Pending: 0
						Tasks Completed: 7938
						Tasks Terminated: 0

WARN
					Metrics after 264 hours:
						Tasks Total: 9618
						Tasks Active: 156
						Tasks Pending: 0
						Tasks Completed: 9462
						Tasks Terminated: 0

WARN
					Metrics after 264 hours:
						Tasks Total: 9618
						Tasks Active: 156
						Tasks Pending: 0
						Tasks Completed: 9462
						Tasks Terminated: 0

WARN
					Metrics after 264 hours:
						Tasks Total: 9618
						Tasks Active: 156
						Tasks Pending: 0
						Tasks Completed: 9462
						Tasks Terminated: 0

WARN
					Metrics after 288 hours:
						Tasks Total: 11069
						Tasks Active: 130
						Tasks Pending: 0
						Tasks Completed: 10939
						Tasks Terminated: 0

WARN
					Metrics after 288 hours:
						Tasks Total: 11069
						Tasks Active: 130
						Tasks Pending: 0
						Tasks Completed: 10939
						Tasks Terminated: 0

WARN
					Metrics after 288 hours:
						Tasks Total: 11069
						Tasks Active: 130
						Tasks Pending: 0
						Tasks Completed: 10939
						Tasks Terminated: 0

WARN
					Metrics after 312 hours:
						Tasks Total: 14997
						Tasks Active: 193
						Tasks Pending: 0
						Tasks Completed: 14804
						Tasks Terminated: 0

WARN
					Metrics after 312 hours:
						Tasks Total: 14997
						Tasks Active: 193
						Tasks Pending: 0
						Tasks Completed: 14804
						Tasks Terminated: 0

WARN
					Metrics after 312 hours:
						Tasks Total: 14997
						Tasks Active: 193
						Tasks Pending: 0
						Tasks Completed: 14804
						Tasks Terminated: 0

WARN
					Metrics after 336 hours:
						Tasks Total: 16752
						Tasks Active: 206
						Tasks Pending: 0
						Tasks Completed: 16546
						Tasks Terminated: 0

WARN
					Metrics after 336 hours:
						Tasks Total: 16752
						Tasks Active: 206
						Tasks Pending: 0
						Tasks Completed: 16546
						Tasks Terminated: 0

WARN
					Metrics after 336 hours:
						Tasks Total: 16752
						Tasks Active: 206
						Tasks Pending: 0
						Tasks Completed: 16546
						Tasks Terminated: 0

WARN
					Metrics after 360 hours:
						Tasks Total: 17933
						Tasks Active: 129
						Tasks Pending: 0
						Tasks Completed: 17804
						Tasks Terminated: 0

WARN
					Metrics after 360 hours:
						Tasks Total: 17933
						Tasks Active: 129
						Tasks Pending: 0
						Tasks Completed: 17804
						Tasks Terminated: 0

WARN
					Metrics after 360 hours:
						Tasks Total: 17933
						Tasks Active: 129
						Tasks Pending: 0
						Tasks Completed: 17804
						Tasks Terminated: 0

WARN
					Metrics after 384 hours:
						Tasks Total: 19072
						Tasks Active: 116
						Tasks Pending: 0
						Tasks Completed: 18956
						Tasks Terminated: 0

WARN
					Metrics after 384 hours:
						Tasks Total: 19072
						Tasks Active: 116
						Tasks Pending: 0
						Tasks Completed: 18956
						Tasks Terminated: 0

WARN
					Metrics after 384 hours:
						Tasks Total: 19072
						Tasks Active: 116
						Tasks Pending: 0
						Tasks Completed: 18956
						Tasks Terminated: 0

WARN
					Metrics after 408 hours:
						Tasks Total: 19427
						Tasks Active: 103
						Tasks Pending: 0
						Tasks Completed: 19324
						Tasks Terminated: 0

WARN
					Metrics after 408 hours:
						Tasks Total: 19427
						Tasks Active: 103
						Tasks Pending: 0
						Tasks Completed: 19324
						Tasks Terminated: 0

WARN
					Metrics after 408 hours:
						Tasks Total: 19427
						Tasks Active: 103
						Tasks Pending: 0
						Tasks Completed: 19324
						Tasks Terminated: 0

WARN
					Metrics after 432 hours:
						Tasks Total: 20937
						Tasks Active: 159
						Tasks Pending: 0
						Tasks Completed: 20778
						Tasks Terminated: 0

WARN
					Metrics after 432 hours:
						Tasks Total: 20937
						Tasks Active: 159
						Tasks Pending: 0
						Tasks Completed: 20778
						Tasks Terminated: 0

WARN
					Metrics after 432 hours:
						Tasks Total: 20937
						Tasks Active: 159
						Tasks Pending: 0
						Tasks Completed: 20778
						Tasks Terminated: 0

WARN
					Metrics after 456 hours:
						Tasks Total: 22387
						Tasks Active: 273
						Tasks Pending: 0
						Tasks Completed: 22114
						Tasks Terminated: 0

WARN
					Metrics after 456 hours:
						Tasks Total: 22387
						Tasks Active: 273
						Tasks Pending: 0
						Tasks Completed: 22114
						Tasks Terminated: 0

WARN
					Metrics after 456 hours:
						Tasks Total: 22387
						Tasks Active: 273
						Tasks Pending: 0
						Tasks Completed: 22114
						Tasks Terminated: 0

WARN
					Metrics after 480 hours:
						Tasks Total: 24301
						Tasks Active: 252
						Tasks Pending: 0
						Tasks Completed: 24049
						Tasks Terminated: 0

WARN
					Metrics after 480 hours:
						Tasks Total: 24301
						Tasks Active: 252
						Tasks Pending: 0
						Tasks Completed: 24049
						Tasks Terminated: 0

WARN
					Metrics after 480 hours:
						Tasks Total: 24301
						Tasks Active: 252
						Tasks Pending: 0
						Tasks Completed: 24049
						Tasks Terminated: 0

WARN
					Metrics after 504 hours:
						Tasks Total: 25880
						Tasks Active: 226
						Tasks Pending: 0
						Tasks Completed: 25654
						Tasks Terminated: 0

WARN
					Metrics after 504 hours:
						Tasks Total: 25880
						Tasks Active: 226
						Tasks Pending: 0
						Tasks Completed: 25654
						Tasks Terminated: 0

WARN
					Metrics after 504 hours:
						Tasks Total: 25880
						Tasks Active: 226
						Tasks Pending: 0
						Tasks Completed: 25654
						Tasks Terminated: 0

WARN
					Metrics after 528 hours:
						Tasks Total: 27270
						Tasks Active: 127
						Tasks Pending: 0
						Tasks Completed: 27143
						Tasks Terminated: 0

WARN
					Metrics after 528 hours:
						Tasks Total: 27270
						Tasks Active: 127
						Tasks Pending: 0
						Tasks Completed: 27143
						Tasks Terminated: 0

WARN
					Metrics after 528 hours:
						Tasks Total: 27270
						Tasks Active: 127
						Tasks Pending: 0
						Tasks Completed: 27143
						Tasks Terminated: 0

WARN
					Metrics after 552 hours:
						Tasks Total: 30122
						Tasks Active: 97
						Tasks Pending: 0
						Tasks Completed: 30025
						Tasks Terminated: 0

WARN
					Metrics after 552 hours:
						Tasks Total: 30122
						Tasks Active: 97
						Tasks Pending: 0
						Tasks Completed: 30025
						Tasks Terminated: 0

WARN
					Metrics after 552 hours:
						Tasks Total: 30122
						Tasks Active: 97
						Tasks Pending: 0
						Tasks Completed: 30025
						Tasks Terminated: 0

WARN
					Metrics after 576 hours:
						Tasks Total: 30674
						Tasks Active: 98
						Tasks Pending: 0
						Tasks Completed: 30576
						Tasks Terminated: 0

WARN
					Metrics after 576 hours:
						Tasks Total: 30674
						Tasks Active: 98
						Tasks Pending: 0
						Tasks Completed: 30576
						Tasks Terminated: 0

WARN
					Metrics after 576 hours:
						Tasks Total: 30674
						Tasks Active: 98
						Tasks Pending: 0
						Tasks Completed: 30576
						Tasks Terminated: 0

WARN
					Metrics after 600 hours:
						Tasks Total: 33314
						Tasks Active: 150
						Tasks Pending: 0
						Tasks Completed: 33164
						Tasks Terminated: 0

WARN
					Metrics after 600 hours:
						Tasks Total: 33314
						Tasks Active: 150
						Tasks Pending: 0
						Tasks Completed: 33164
						Tasks Terminated: 0

WARN
					Metrics after 600 hours:
						Tasks Total: 33314
						Tasks Active: 150
						Tasks Pending: 0
						Tasks Completed: 33164
						Tasks Terminated: 0

WARN
					Metrics after 624 hours:
						Tasks Total: 35894
						Tasks Active: 163
						Tasks Pending: 0
						Tasks Completed: 35731
						Tasks Terminated: 0

WARN
					Metrics after 624 hours:
						Tasks Total: 35894
						Tasks Active: 163
						Tasks Pending: 0
						Tasks Completed: 35731
						Tasks Terminated: 0

WARN
					Metrics after 624 hours:
						Tasks Total: 35894
						Tasks Active: 163
						Tasks Pending: 0
						Tasks Completed: 35731
						Tasks Terminated: 0

WARN
					Metrics after 648 hours:
						Tasks Total: 39943
						Tasks Active: 253
						Tasks Pending: 0
						Tasks Completed: 39690
						Tasks Terminated: 0

WARN
					Metrics after 648 hours:
						Tasks Total: 39943
						Tasks Active: 253
						Tasks Pending: 0
						Tasks Completed: 39690
						Tasks Terminated: 0

WARN
					Metrics after 648 hours:
						Tasks Total: 39943
						Tasks Active: 253
						Tasks Pending: 0
						Tasks Completed: 39690
						Tasks Terminated: 0

WARN
					Metrics after 672 hours:
						Tasks Total: 42909
						Tasks Active: 114
						Tasks Pending: 0
						Tasks Completed: 42795
						Tasks Terminated: 0

WARN
					Metrics after 672 hours:
						Tasks Total: 42909
						Tasks Active: 114
						Tasks Pending: 0
						Tasks Completed: 42795
						Tasks Terminated: 0

WARN
					Metrics after 672 hours:
						Tasks Total: 42909
						Tasks Active: 114
						Tasks Pending: 0
						Tasks Completed: 42795
						Tasks Terminated: 0

WARN
					Metrics after 696 hours:
						Tasks Total: 46868
						Tasks Active: 111
						Tasks Pending: 0
						Tasks Completed: 46757
						Tasks Terminated: 0

WARN
					Metrics after 696 hours:
						Tasks Total: 46868
						Tasks Active: 111
						Tasks Pending: 0
						Tasks Completed: 46757
						Tasks Terminated: 0

WARN
					Metrics after 696 hours:
						Tasks Total: 46868
						Tasks Active: 111
						Tasks Pending: 0
						Tasks Completed: 46757
						Tasks Terminated: 0

WARN
					Metrics after 720 hours:
						Tasks Total: 47022
						Tasks Active: 79
						Tasks Pending: 0
						Tasks Completed: 46943
						Tasks Terminated: 0

WARN
					Metrics after 720 hours:
						Tasks Total: 47022
						Tasks Active: 79
						Tasks Pending: 0
						Tasks Completed: 46943
						Tasks Terminated: 0

WARN
					Metrics after 720 hours:
						Tasks Total: 47022
						Tasks Active: 79
						Tasks Pending: 0
						Tasks Completed: 46943
						Tasks Terminated: 0

WARN
					Metrics after 744 hours:
						Tasks Total: 47117
						Tasks Active: 73
						Tasks Pending: 0
						Tasks Completed: 47044
						Tasks Terminated: 0

WARN
					Metrics after 744 hours:
						Tasks Total: 47117
						Tasks Active: 73
						Tasks Pending: 0
						Tasks Completed: 47044
						Tasks Terminated: 0

WARN
					Metrics after 744 hours:
						Tasks Total: 47117
						Tasks Active: 73
						Tasks Pending: 0
						Tasks Completed: 47044
						Tasks Terminated: 0

Starting replay

WARN
					Metrics after 24 hours:
						Tasks Total: 1172
						Tasks Active: 136
						Tasks Pending: 0
						Tasks Completed: 1036
						Tasks Terminated: 0

WARN
					Metrics after 24 hours:
						Tasks Total: 1172
						Tasks Active: 136
						Tasks Pending: 0
						Tasks Completed: 1036
						Tasks Terminated: 0

WARN
					Metrics after 24 hours:
						Tasks Total: 1172
						Tasks Active: 136
						Tasks Pending: 0
						Tasks Completed: 1036
						Tasks Terminated: 0

WARN
					Metrics after 48 hours:
						Tasks Total: 1413
						Tasks Active: 29
						Tasks Pending: 0
						Tasks Completed: 1384
						Tasks Terminated: 0

WARN
					Metrics after 48 hours:
						Tasks Total: 1413
						Tasks Active: 29
						Tasks Pending: 0
						Tasks Completed: 1384
						Tasks Terminated: 0

WARN
					Metrics after 48 hours:
						Tasks Total: 1413
						Tasks Active: 29
						Tasks Pending: 0
						Tasks Completed: 1384
						Tasks Terminated: 0

WARN
					Metrics after 72 hours:
						Tasks Total: 1608
						Tasks Active: 21
						Tasks Pending: 0
						Tasks Completed: 1587
						Tasks Terminated: 0

WARN
					Metrics after 72 hours:
						Tasks Total: 1608
						Tasks Active: 21
						Tasks Pending: 0
						Tasks Completed: 1587
						Tasks Terminated: 0

WARN
					Metrics after 72 hours:
						Tasks Total: 1608
						Tasks Active: 21
						Tasks Pending: 0
						Tasks Completed: 1587
						Tasks Terminated: 0

WARN
					Metrics after 96 hours:
						Tasks Total: 3087
						Tasks Active: 35
						Tasks Pending: 0
						Tasks Completed: 3052
						Tasks Terminated: 0

WARN
					Metrics after 96 hours:
						Tasks Total: 3087
						Tasks Active: 35
						Tasks Pending: 0
						Tasks Completed: 3052
						Tasks Terminated: 0

WARN
					Metrics after 96 hours:
						Tasks Total: 3087
						Tasks Active: 35
						Tasks Pending: 0
						Tasks Completed: 3052
						Tasks Terminated: 0

WARN
					Metrics after 120 hours:
						Tasks Total: 4613
						Tasks Active: 32
						Tasks Pending: 0
						Tasks Completed: 4581
						Tasks Terminated: 0

WARN
					Metrics after 120 hours:
						Tasks Total: 4613
						Tasks Active: 32
						Tasks Pending: 0
						Tasks Completed: 4581
						Tasks Terminated: 0

WARN
					Metrics after 120 hours:
						Tasks Total: 4613
						Tasks Active: 32
						Tasks Pending: 0
						Tasks Completed: 4581
						Tasks Terminated: 0

WARN
					Metrics after 144 hours:
						Tasks Total: 5491
						Tasks Active: 41
						Tasks Pending: 0
						Tasks Completed: 5450
						Tasks Terminated: 0

WARN
					Metrics after 144 hours:
						Tasks Total: 5491
						Tasks Active: 41
						Tasks Pending: 0
						Tasks Completed: 5450
						Tasks Terminated: 0

WARN
					Metrics after 144 hours:
						Tasks Total: 5491
						Tasks Active: 41
						Tasks Pending: 0
						Tasks Completed: 5450
						Tasks Terminated: 0

WARN
					Metrics after 168 hours:
						Tasks Total: 5969
						Tasks Active: 54
						Tasks Pending: 0
						Tasks Completed: 5915
						Tasks Terminated: 0

WARN
					Metrics after 168 hours:
						Tasks Total: 5969
						Tasks Active: 54
						Tasks Pending: 0
						Tasks Completed: 5915
						Tasks Terminated: 0

WARN
					Metrics after 168 hours:
						Tasks Total: 5969
						Tasks Active: 54
						Tasks Pending: 0
						Tasks Completed: 5915
						Tasks Terminated: 0

WARN
					Metrics after 192 hours:
						Tasks Total: 6794
						Tasks Active: 66
						Tasks Pending: 0
						Tasks Completed: 6728
						Tasks Terminated: 0

WARN
					Metrics after 192 hours:
						Tasks Total: 6794
						Tasks Active: 66
						Tasks Pending: 0
						Tasks Completed: 6728
						Tasks Terminated: 0

WARN
					Metrics after 192 hours:
						Tasks Total: 6794
						Tasks Active: 66
						Tasks Pending: 0
						Tasks Completed: 6728
						Tasks Terminated: 0

WARN
					Metrics after 216 hours:
						Tasks Total: 7314
						Tasks Active: 74
						Tasks Pending: 0
						Tasks Completed: 7240
						Tasks Terminated: 0

WARN
					Metrics after 216 hours:
						Tasks Total: 7314
						Tasks Active: 74
						Tasks Pending: 0
						Tasks Completed: 7240
						Tasks Terminated: 0

WARN
					Metrics after 216 hours:
						Tasks Total: 7314
						Tasks Active: 74
						Tasks Pending: 0
						Tasks Completed: 7240
						Tasks Terminated: 0

WARN
					Metrics after 240 hours:
						Tasks Total: 7977
						Tasks Active: 39
						Tasks Pending: 0
						Tasks Completed: 7938
						Tasks Terminated: 0

WARN
					Metrics after 240 hours:
						Tasks Total: 7977
						Tasks Active: 39
						Tasks Pending: 0
						Tasks Completed: 7938
						Tasks Terminated: 0

WARN
					Metrics after 240 hours:
						Tasks Total: 7977
						Tasks Active: 39
						Tasks Pending: 0
						Tasks Completed: 7938
						Tasks Terminated: 0

WARN
					Metrics after 264 hours:
						Tasks Total: 9618
						Tasks Active: 156
						Tasks Pending: 0
						Tasks Completed: 9462
						Tasks Terminated: 0

WARN
					Metrics after 264 hours:
						Tasks Total: 9618
						Tasks Active: 156
						Tasks Pending: 0
						Tasks Completed: 9462
						Tasks Terminated: 0

WARN
					Metrics after 264 hours:
						Tasks Total: 9618
						Tasks Active: 156
						Tasks Pending: 0
						Tasks Completed: 9462
						Tasks Terminated: 0

WARN
					Metrics after 288 hours:
						Tasks Total: 11069
						Tasks Active: 130
						Tasks Pending: 0
						Tasks Completed: 10939
						Tasks Terminated: 0

WARN
					Metrics after 288 hours:
						Tasks Total: 11069
						Tasks Active: 130
						Tasks Pending: 0
						Tasks Completed: 10939
						Tasks Terminated: 0

WARN
					Metrics after 288 hours:
						Tasks Total: 11069
						Tasks Active: 130
						Tasks Pending: 0
						Tasks Completed: 10939
						Tasks Terminated: 0

WARN
					Metrics after 312 hours:
						Tasks Total: 14997
						Tasks Active: 193
						Tasks Pending: 0
						Tasks Completed: 14804
						Tasks Terminated: 0

WARN
					Metrics after 312 hours:
						Tasks Total: 14997
						Tasks Active: 193
						Tasks Pending: 0
						Tasks Completed: 14804
						Tasks Terminated: 0

WARN
					Metrics after 312 hours:
						Tasks Total: 14997
						Tasks Active: 193
						Tasks Pending: 0
						Tasks Completed: 14804
						Tasks Terminated: 0

WARN
					Metrics after 336 hours:
						Tasks Total: 16752
						Tasks Active: 206
						Tasks Pending: 0
						Tasks Completed: 16546
						Tasks Terminated: 0

WARN
					Metrics after 336 hours:
						Tasks Total: 16752
						Tasks Active: 206
						Tasks Pending: 0
						Tasks Completed: 16546
						Tasks Terminated: 0

WARN
					Metrics after 336 hours:
						Tasks Total: 16752
						Tasks Active: 206
						Tasks Pending: 0
						Tasks Completed: 16546
						Tasks Terminated: 0

WARN
					Metrics after 360 hours:
						Tasks Total: 17933
						Tasks Active: 129
						Tasks Pending: 0
						Tasks Completed: 17804
						Tasks Terminated: 0

WARN
					Metrics after 360 hours:
						Tasks Total: 17933
						Tasks Active: 129
						Tasks Pending: 0
						Tasks Completed: 17804
						Tasks Terminated: 0

WARN
					Metrics after 360 hours:
						Tasks Total: 17933
						Tasks Active: 129
						Tasks Pending: 0
						Tasks Completed: 17804
						Tasks Terminated: 0

WARN
					Metrics after 384 hours:
						Tasks Total: 19072
						Tasks Active: 116
						Tasks Pending: 0
						Tasks Completed: 18956
						Tasks Terminated: 0

WARN
					Metrics after 384 hours:
						Tasks Total: 19072
						Tasks Active: 116
						Tasks Pending: 0
						Tasks Completed: 18956
						Tasks Terminated: 0

WARN
					Metrics after 384 hours:
						Tasks Total: 19072
						Tasks Active: 116
						Tasks Pending: 0
						Tasks Completed: 18956
						Tasks Terminated: 0

WARN
					Metrics after 408 hours:
						Tasks Total: 19427
						Tasks Active: 103
						Tasks Pending: 0
						Tasks Completed: 19324
						Tasks Terminated: 0

WARN
					Metrics after 408 hours:
						Tasks Total: 19427
						Tasks Active: 103
						Tasks Pending: 0
						Tasks Completed: 19324
						Tasks Terminated: 0

WARN
					Metrics after 408 hours:
						Tasks Total: 19427
						Tasks Active: 103
						Tasks Pending: 0
						Tasks Completed: 19324
						Tasks Terminated: 0

WARN
					Metrics after 432 hours:
						Tasks Total: 20937
						Tasks Active: 159
						Tasks Pending: 0
						Tasks Completed: 20778
						Tasks Terminated: 0

WARN
					Metrics after 432 hours:
						Tasks Total: 20937
						Tasks Active: 159
						Tasks Pending: 0
						Tasks Completed: 20778
						Tasks Terminated: 0

WARN
					Metrics after 432 hours:
						Tasks Total: 20937
						Tasks Active: 159
						Tasks Pending: 0
						Tasks Completed: 20778
						Tasks Terminated: 0

WARN
					Metrics after 456 hours:
						Tasks Total: 22387
						Tasks Active: 273
						Tasks Pending: 0
						Tasks Completed: 22114
						Tasks Terminated: 0

WARN
					Metrics after 456 hours:
						Tasks Total: 22387
						Tasks Active: 273
						Tasks Pending: 0
						Tasks Completed: 22114
						Tasks Terminated: 0

WARN
					Metrics after 456 hours:
						Tasks Total: 22387
						Tasks Active: 273
						Tasks Pending: 0
						Tasks Completed: 22114
						Tasks Terminated: 0

WARN
					Metrics after 480 hours:
						Tasks Total: 24301
						Tasks Active: 252
						Tasks Pending: 0
						Tasks Completed: 24049
						Tasks Terminated: 0

WARN
					Metrics after 480 hours:
						Tasks Total: 24301
						Tasks Active: 252
						Tasks Pending: 0
						Tasks Completed: 24049
						Tasks Terminated: 0

WARN
					Metrics after 480 hours:
						Tasks Total: 24301
						Tasks Active: 252
						Tasks Pending: 0
						Tasks Completed: 24049
						Tasks Terminated: 0

WARN
					Metrics after 504 hours:
						Tasks Total: 25880
						Tasks Active: 226
						Tasks Pending: 0
						Tasks Completed: 25654
						Tasks Terminated: 0

WARN
					Metrics after 504 hours:
						Tasks Total: 25880
						Tasks Active: 226
						Tasks Pending: 0
						Tasks Completed: 25654
						Tasks Terminated: 0

WARN
					Metrics after 504 hours:
						Tasks Total: 25880
						Tasks Active: 226
						Tasks Pending: 0
						Tasks Completed: 25654
						Tasks Terminated: 0

WARN
					Metrics after 528 hours:
						Tasks Total: 27270
						Tasks Active: 127
						Tasks Pending: 0
						Tasks Completed: 27143
						Tasks Terminated: 0

WARN
					Metrics after 528 hours:
						Tasks Total: 27270
						Tasks Active: 127
						Tasks Pending: 0
						Tasks Completed: 27143
						Tasks Terminated: 0

WARN
					Metrics after 528 hours:
						Tasks Total: 27270
						Tasks Active: 127
						Tasks Pending: 0
						Tasks Completed: 27143
						Tasks Terminated: 0

WARN
					Metrics after 552 hours:
						Tasks Total: 30122
						Tasks Active: 97
						Tasks Pending: 0
						Tasks Completed: 30025
						Tasks Terminated: 0

WARN
					Metrics after 552 hours:
						Tasks Total: 30122
						Tasks Active: 97
						Tasks Pending: 0
						Tasks Completed: 30025
						Tasks Terminated: 0

WARN
					Metrics after 552 hours:
						Tasks Total: 30122
						Tasks Active: 97
						Tasks Pending: 0
						Tasks Completed: 30025
						Tasks Terminated: 0

WARN
					Metrics after 576 hours:
						Tasks Total: 30674
						Tasks Active: 98
						Tasks Pending: 0
						Tasks Completed: 30576
						Tasks Terminated: 0

WARN
					Metrics after 576 hours:
						Tasks Total: 30674
						Tasks Active: 98
						Tasks Pending: 0
						Tasks Completed: 30576
						Tasks Terminated: 0

WARN
					Metrics after 576 hours:
						Tasks Total: 30674
						Tasks Active: 98
						Tasks Pending: 0
						Tasks Completed: 30576
						Tasks Terminated: 0

WARN
					Metrics after 600 hours:
						Tasks Total: 33314
						Tasks Active: 150
						Tasks Pending: 0
						Tasks Completed: 33164
						Tasks Terminated: 0

WARN
					Metrics after 600 hours:
						Tasks Total: 33314
						Tasks Active: 150
						Tasks Pending: 0
						Tasks Completed: 33164
						Tasks Terminated: 0

WARN
					Metrics after 600 hours:
						Tasks Total: 33314
						Tasks Active: 150
						Tasks Pending: 0
						Tasks Completed: 33164
						Tasks Terminated: 0

WARN
					Metrics after 624 hours:
						Tasks Total: 35894
						Tasks Active: 163
						Tasks Pending: 0
						Tasks Completed: 35731
						Tasks Terminated: 0

WARN
					Metrics after 624 hours:
						Tasks Total: 35894
						Tasks Active: 163
						Tasks Pending: 0
						Tasks Completed: 35731
						Tasks Terminated: 0

WARN
					Metrics after 624 hours:
						Tasks Total: 35894
						Tasks Active: 163
						Tasks Pending: 0
						Tasks Completed: 35731
						Tasks Terminated: 0

WARN
					Metrics after 648 hours:
						Tasks Total: 39943
						Tasks Active: 253
						Tasks Pending: 0
						Tasks Completed: 39690
						Tasks Terminated: 0

WARN
					Metrics after 648 hours:
						Tasks Total: 39943
						Tasks Active: 253
						Tasks Pending: 0
						Tasks Completed: 39690
						Tasks Terminated: 0

WARN
					Metrics after 648 hours:
						Tasks Total: 39943
						Tasks Active: 253
						Tasks Pending: 0
						Tasks Completed: 39690
						Tasks Terminated: 0

WARN
					Metrics after 672 hours:
						Tasks Total: 42909
						Tasks Active: 114
						Tasks Pending: 0
						Tasks Completed: 42795
						Tasks Terminated: 0

WARN
					Metrics after 672 hours:
						Tasks Total: 42909
						Tasks Active: 114
						Tasks Pending: 0
						Tasks Completed: 42795
						Tasks Terminated: 0

WARN
					Metrics after 672 hours:
						Tasks Total: 42909
						Tasks Active: 114
						Tasks Pending: 0
						Tasks Completed: 42795
						Tasks Terminated: 0

WARN
					Metrics after 696 hours:
						Tasks Total: 46868
						Tasks Active: 111
						Tasks Pending: 0
						Tasks Completed: 46757
						Tasks Terminated: 0

WARN
					Metrics after 696 hours:
						Tasks Total: 46868
						Tasks Active: 111
						Tasks Pending: 0
						Tasks Completed: 46757
						Tasks Terminated: 0

WARN
					Metrics after 696 hours:
						Tasks Total: 46868
						Tasks Active: 111
						Tasks Pending: 0
						Tasks Completed: 46757
						Tasks Terminated: 0

WARN
					Metrics after 720 hours:
						Tasks Total: 47022
						Tasks Active: 79
						Tasks Pending: 0
						Tasks Completed: 46943
						Tasks Terminated: 0

WARN
					Metrics after 720 hours:
						Tasks Total: 47022
						Tasks Active: 79
						Tasks Pending: 0
						Tasks Completed: 46943
						Tasks Terminated: 0

WARN
					Metrics after 720 hours:
						Tasks Total: 47022
						Tasks Active: 79
						Tasks Pending: 0
						Tasks Completed: 46943
						Tasks Terminated: 0

WARN
					Metrics after 744 hours:
						Tasks Total: 47117
						Tasks Active: 73
						Tasks Pending: 0
						Tasks Completed: 47044
						Tasks Terminated: 0

WARN
					Metrics after 744 hours:
						Tasks Total: 47117
						Tasks Active: 73
						Tasks Pending: 0
						Tasks Completed: 47044
						Tasks Terminated: 0

WARN
					Metrics after 744 hours:
						Tasks Total: 47117
						Tasks Active: 73
						Tasks Pending: 0
						Tasks Completed: 47044
						Tasks Terminated: 0

Starting replay

WARN
					Metrics after 24 hours:
						Tasks Total: 1172
						Tasks Active: 136
						Tasks Pending: 0
						Tasks Completed: 1036
						Tasks Terminated: 0

WARN
					Metrics after 24 hours:
						Tasks Total: 1172
						Tasks Active: 136
						Tasks Pending: 0
						Tasks Completed: 1036
						Tasks Terminated: 0

WARN
					Metrics after 24 hours:
						Tasks Total: 1172
						Tasks Active: 136
						Tasks Pending: 0
						Tasks Completed: 1036
						Tasks Terminated: 0

WARN
					Metrics after 48 hours:
						Tasks Total: 1413
						Tasks Active: 29
						Tasks Pending: 0
						Tasks Completed: 1384
						Tasks Terminated: 0

WARN
					Metrics after 48 hours:
						Tasks Total: 1413
						Tasks Active: 29
						Tasks Pending: 0
						Tasks Completed: 1384
						Tasks Terminated: 0

WARN
					Metrics after 48 hours:
						Tasks Total: 1413
						Tasks Active: 29
						Tasks Pending: 0
						Tasks Completed: 1384
						Tasks Terminated: 0

WARN
					Metrics after 72 hours:
						Tasks Total: 1608
						Tasks Active: 21
						Tasks Pending: 0
						Tasks Completed: 1587
						Tasks Terminated: 0

WARN
					Metrics after 72 hours:
						Tasks Total: 1608
						Tasks Active: 21
						Tasks Pending: 0
						Tasks Completed: 1587
						Tasks Terminated: 0

WARN
					Metrics after 72 hours:
						Tasks Total: 1608
						Tasks Active: 21
						Tasks Pending: 0
						Tasks Completed: 1587
						Tasks Terminated: 0

WARN
					Metrics after 96 hours:
						Tasks Total: 3087
						Tasks Active: 35
						Tasks Pending: 0
						Tasks Completed: 3052
						Tasks Terminated: 0

WARN
					Metrics after 96 hours:
						Tasks Total: 3087
						Tasks Active: 35
						Tasks Pending: 0
						Tasks Completed: 3052
						Tasks Terminated: 0

WARN
					Metrics after 96 hours:
						Tasks Total: 3087
						Tasks Active: 35
						Tasks Pending: 0
						Tasks Completed: 3052
						Tasks Terminated: 0

WARN
					Metrics after 120 hours:
						Tasks Total: 4613
						Tasks Active: 32
						Tasks Pending: 0
						Tasks Completed: 4581
						Tasks Terminated: 0

WARN
					Metrics after 120 hours:
						Tasks Total: 4613
						Tasks Active: 32
						Tasks Pending: 0
						Tasks Completed: 4581
						Tasks Terminated: 0

WARN
					Metrics after 120 hours:
						Tasks Total: 4613
						Tasks Active: 32
						Tasks Pending: 0
						Tasks Completed: 4581
						Tasks Terminated: 0

WARN
					Metrics after 144 hours:
						Tasks Total: 5491
						Tasks Active: 41
						Tasks Pending: 0
						Tasks Completed: 5450
						Tasks Terminated: 0

WARN
					Metrics after 144 hours:
						Tasks Total: 5491
						Tasks Active: 41
						Tasks Pending: 0
						Tasks Completed: 5450
						Tasks Terminated: 0

WARN
					Metrics after 144 hours:
						Tasks Total: 5491
						Tasks Active: 41
						Tasks Pending: 0
						Tasks Completed: 5450
						Tasks Terminated: 0

WARN
					Metrics after 168 hours:
						Tasks Total: 5969
						Tasks Active: 54
						Tasks Pending: 0
						Tasks Completed: 5915
						Tasks Terminated: 0

WARN
					Metrics after 168 hours:
						Tasks Total: 5969
						Tasks Active: 54
						Tasks Pending: 0
						Tasks Completed: 5915
						Tasks Terminated: 0

WARN
					Metrics after 168 hours:
						Tasks Total: 5969
						Tasks Active: 54
						Tasks Pending: 0
						Tasks Completed: 5915
						Tasks Terminated: 0

WARN
					Metrics after 192 hours:
						Tasks Total: 6794
						Tasks Active: 66
						Tasks Pending: 0
						Tasks Completed: 6728
						Tasks Terminated: 0

WARN
					Metrics after 192 hours:
						Tasks Total: 6794
						Tasks Active: 66
						Tasks Pending: 0
						Tasks Completed: 6728
						Tasks Terminated: 0

WARN
					Metrics after 192 hours:
						Tasks Total: 6794
						Tasks Active: 66
						Tasks Pending: 0
						Tasks Completed: 6728
						Tasks Terminated: 0

WARN
					Metrics after 216 hours:
						Tasks Total: 7314
						Tasks Active: 74
						Tasks Pending: 0
						Tasks Completed: 7240
						Tasks Terminated: 0

WARN
					Metrics after 216 hours:
						Tasks Total: 7314
						Tasks Active: 74
						Tasks Pending: 0
						Tasks Completed: 7240
						Tasks Terminated: 0

WARN
					Metrics after 216 hours:
						Tasks Total: 7314
						Tasks Active: 74
						Tasks Pending: 0
						Tasks Completed: 7240
						Tasks Terminated: 0

WARN
					Metrics after 240 hours:
						Tasks Total: 7977
						Tasks Active: 39
						Tasks Pending: 0
						Tasks Completed: 7938
						Tasks Terminated: 0

WARN
					Metrics after 240 hours:
						Tasks Total: 7977
						Tasks Active: 39
						Tasks Pending: 0
						Tasks Completed: 7938
						Tasks Terminated: 0

WARN
					Metrics after 240 hours:
						Tasks Total: 7977
						Tasks Active: 39
						Tasks Pending: 0
						Tasks Completed: 7938
						Tasks Terminated: 0

WARN
					Metrics after 264 hours:
						Tasks Total: 9618
						Tasks Active: 156
						Tasks Pending: 0
						Tasks Completed: 9462
						Tasks Terminated: 0

WARN
					Metrics after 264 hours:
						Tasks Total: 9618
						Tasks Active: 156
						Tasks Pending: 0
						Tasks Completed: 9462
						Tasks Terminated: 0

WARN
					Metrics after 264 hours:
						Tasks Total: 9618
						Tasks Active: 156
						Tasks Pending: 0
						Tasks Completed: 9462
						Tasks Terminated: 0

WARN
					Metrics after 288 hours:
						Tasks Total: 11069
						Tasks Active: 130
						Tasks Pending: 0
						Tasks Completed: 10939
						Tasks Terminated: 0

WARN
					Metrics after 288 hours:
						Tasks Total: 11069
						Tasks Active: 130
						Tasks Pending: 0
						Tasks Completed: 10939
						Tasks Terminated: 0

WARN
					Metrics after 288 hours:
						Tasks Total: 11069
						Tasks Active: 130
						Tasks Pending: 0
						Tasks Completed: 10939
						Tasks Terminated: 0

WARN
					Metrics after 312 hours:
						Tasks Total: 14997
						Tasks Active: 193
						Tasks Pending: 0
						Tasks Completed: 14804
						Tasks Terminated: 0

WARN
					Metrics after 312 hours:
						Tasks Total: 14997
						Tasks Active: 193
						Tasks Pending: 0
						Tasks Completed: 14804
						Tasks Terminated: 0

WARN
					Metrics after 312 hours:
						Tasks Total: 14997
						Tasks Active: 193
						Tasks Pending: 0
						Tasks Completed: 14804
						Tasks Terminated: 0

WARN
					Metrics after 336 hours:
						Tasks Total: 16752
						Tasks Active: 206
						Tasks Pending: 0
						Tasks Completed: 16546
						Tasks Terminated: 0

WARN
					Metrics after 336 hours:
						Tasks Total: 16752
						Tasks Active: 206
						Tasks Pending: 0
						Tasks Completed: 16546
						Tasks Terminated: 0

WARN
					Metrics after 336 hours:
						Tasks Total: 16752
						Tasks Active: 206
						Tasks Pending: 0
						Tasks Completed: 16546
						Tasks Terminated: 0

WARN
					Metrics after 360 hours:
						Tasks Total: 17933
						Tasks Active: 129
						Tasks Pending: 0
						Tasks Completed: 17804
						Tasks Terminated: 0

WARN
					Metrics after 360 hours:
						Tasks Total: 17933
						Tasks Active: 129
						Tasks Pending: 0
						Tasks Completed: 17804
						Tasks Terminated: 0

WARN
					Metrics after 360 hours:
						Tasks Total: 17933
						Tasks Active: 129
						Tasks Pending: 0
						Tasks Completed: 17804
						Tasks Terminated: 0

WARN
					Metrics after 384 hours:
						Tasks Total: 19072
						Tasks Active: 116
						Tasks Pending: 0
						Tasks Completed: 18956
						Tasks Terminated: 0

WARN
					Metrics after 384 hours:
						Tasks Total: 19072
						Tasks Active: 116
						Tasks Pending: 0
						Tasks Completed: 18956
						Tasks Terminated: 0

WARN
					Metrics after 384 hours:
						Tasks Total: 19072
						Tasks Active: 116
						Tasks Pending: 0
						Tasks Completed: 18956
						Tasks Terminated: 0

WARN
					Metrics after 408 hours:
						Tasks Total: 19427
						Tasks Active: 103
						Tasks Pending: 0
						Tasks Completed: 19324
						Tasks Terminated: 0

WARN
					Metrics after 408 hours:
						Tasks Total: 19427
						Tasks Active: 103
						Tasks Pending: 0
						Tasks Completed: 19324
						Tasks Terminated: 0

WARN
					Metrics after 408 hours:
						Tasks Total: 19427
						Tasks Active: 103
						Tasks Pending: 0
						Tasks Completed: 19324
						Tasks Terminated: 0

WARN
					Metrics after 432 hours:
						Tasks Total: 20937
						Tasks Active: 159
						Tasks Pending: 0
						Tasks Completed: 20778
						Tasks Terminated: 0

WARN
					Metrics after 432 hours:
						Tasks Total: 20937
						Tasks Active: 159
						Tasks Pending: 0
						Tasks Completed: 20778
						Tasks Terminated: 0

WARN
					Metrics after 432 hours:
						Tasks Total: 20937
						Tasks Active: 159
						Tasks Pending: 0
						Tasks Completed: 20778
						Tasks Terminated: 0

WARN
					Metrics after 456 hours:
						Tasks Total: 22387
						Tasks Active: 273
						Tasks Pending: 0
						Tasks Completed: 22114
						Tasks Terminated: 0

WARN
					Metrics after 456 hours:
						Tasks Total: 22387
						Tasks Active: 273
						Tasks Pending: 0
						Tasks Completed: 22114
						Tasks Terminated: 0

WARN
					Metrics after 456 hours:
						Tasks Total: 22387
						Tasks Active: 273
						Tasks Pending: 0
						Tasks Completed: 22114
						Tasks Terminated: 0

WARN
					Metrics after 480 hours:
						Tasks Total: 24301
						Tasks Active: 252
						Tasks Pending: 0
						Tasks Completed: 24049
						Tasks Terminated: 0

WARN
					Metrics after 480 hours:
						Tasks Total: 24301
						Tasks Active: 252
						Tasks Pending: 0
						Tasks Completed: 24049
						Tasks Terminated: 0

WARN
					Metrics after 480 hours:
						Tasks Total: 24301
						Tasks Active: 252
						Tasks Pending: 0
						Tasks Completed: 24049
						Tasks Terminated: 0

WARN
					Metrics after 504 hours:
						Tasks Total: 25880
						Tasks Active: 226
						Tasks Pending: 0
						Tasks Completed: 25654
						Tasks Terminated: 0

WARN
					Metrics after 504 hours:
						Tasks Total: 25880
						Tasks Active: 226
						Tasks Pending: 0
						Tasks Completed: 25654
						Tasks Terminated: 0

WARN
					Metrics after 504 hours:
						Tasks Total: 25880
						Tasks Active: 226
						Tasks Pending: 0
						Tasks Completed: 25654
						Tasks Terminated: 0

WARN
					Metrics after 528 hours:
						Tasks Total: 27270
						Tasks Active: 127
						Tasks Pending: 0
						Tasks Completed: 27143
						Tasks Terminated: 0

WARN
					Metrics after 528 hours:
						Tasks Total: 27270
						Tasks Active: 127
						Tasks Pending: 0
						Tasks Completed: 27143
						Tasks Terminated: 0

WARN
					Metrics after 528 hours:
						Tasks Total: 27270
						Tasks Active: 127
						Tasks Pending: 0
						Tasks Completed: 27143
						Tasks Terminated: 0

WARN
					Metrics after 552 hours:
						Tasks Total: 30122
						Tasks Active: 97
						Tasks Pending: 0
						Tasks Completed: 30025
						Tasks Terminated: 0

WARN
					Metrics after 552 hours:
						Tasks Total: 30122
						Tasks Active: 97
						Tasks Pending: 0
						Tasks Completed: 30025
						Tasks Terminated: 0

WARN
					Metrics after 552 hours:
						Tasks Total: 30122
						Tasks Active: 97
						Tasks Pending: 0
						Tasks Completed: 30025
						Tasks Terminated: 0

WARN
					Metrics after 576 hours:
						Tasks Total: 30674
						Tasks Active: 98
						Tasks Pending: 0
						Tasks Completed: 30576
						Tasks Terminated: 0

WARN
					Metrics after 576 hours:
						Tasks Total: 30674
						Tasks Active: 98
						Tasks Pending: 0
						Tasks Completed: 30576
						Tasks Terminated: 0

WARN
					Metrics after 576 hours:
						Tasks Total: 30674
						Tasks Active: 98
						Tasks Pending: 0
						Tasks Completed: 30576
						Tasks Terminated: 0

WARN
					Metrics after 600 hours:
						Tasks Total: 33314
						Tasks Active: 150
						Tasks Pending: 0
						Tasks Completed: 33164
						Tasks Terminated: 0

WARN
					Metrics after 600 hours:
						Tasks Total: 33314
						Tasks Active: 150
						Tasks Pending: 0
						Tasks Completed: 33164
						Tasks Terminated: 0

WARN
					Metrics after 600 hours:
						Tasks Total: 33314
						Tasks Active: 150
						Tasks Pending: 0
						Tasks Completed: 33164
						Tasks Terminated: 0

WARN
					Metrics after 624 hours:
						Tasks Total: 35894
						Tasks Active: 163
						Tasks Pending: 0
						Tasks Completed: 35731
						Tasks Terminated: 0

WARN
					Metrics after 624 hours:
						Tasks Total: 35894
						Tasks Active: 163
						Tasks Pending: 0
						Tasks Completed: 35731
						Tasks Terminated: 0

WARN
					Metrics after 624 hours:
						Tasks Total: 35894
						Tasks Active: 163
						Tasks Pending: 0
						Tasks Completed: 35731
						Tasks Terminated: 0

WARN
					Metrics after 648 hours:
						Tasks Total: 39943
						Tasks Active: 253
						Tasks Pending: 0
						Tasks Completed: 39690
						Tasks Terminated: 0

WARN
					Metrics after 648 hours:
						Tasks Total: 39943
						Tasks Active: 253
						Tasks Pending: 0
						Tasks Completed: 39690
						Tasks Terminated: 0

WARN
					Metrics after 648 hours:
						Tasks Total: 39943
						Tasks Active: 253
						Tasks Pending: 0
						Tasks Completed: 39690
						Tasks Terminated: 0

WARN
					Metrics after 672 hours:
						Tasks Total: 42909
						Tasks Active: 114
						Tasks Pending: 0
						Tasks Completed: 42795
						Tasks Terminated: 0

WARN
					Metrics after 672 hours:
						Tasks Total: 42909
						Tasks Active: 114
						Tasks Pending: 0
						Tasks Completed: 42795
						Tasks Terminated: 0

WARN
					Metrics after 672 hours:
						Tasks Total: 42909
						Tasks Active: 114
						Tasks Pending: 0
						Tasks Completed: 42795
						Tasks Terminated: 0

WARN
					Metrics after 696 hours:
						Tasks Total: 46868
						Tasks Active: 111
						Tasks Pending: 0
						Tasks Completed: 46757
						Tasks Terminated: 0

WARN
					Metrics after 696 hours:
						Tasks Total: 46868
						Tasks Active: 111
						Tasks Pending: 0
						Tasks Completed: 46757
						Tasks Terminated: 0

WARN
					Metrics after 696 hours:
						Tasks Total: 46868
						Tasks Active: 111
						Tasks Pending: 0
						Tasks Completed: 46757
						Tasks Terminated: 0

WARN
					Metrics after 720 hours:
						Tasks Total: 47022
						Tasks Active: 79
						Tasks Pending: 0
						Tasks Completed: 46943
						Tasks Terminated: 0

WARN
					Metrics after 720 hours:
						Tasks Total: 47022
						Tasks Active: 79
						Tasks Pending: 0
						Tasks Completed: 46943
						Tasks Terminated: 0

WARN
					Metrics after 720 hours:
						Tasks Total: 47022
						Tasks Active: 79
						Tasks Pending: 0
						Tasks Completed: 46943
						Tasks Terminated: 0

WARN
					Metrics after 744 hours:
						Tasks Total: 47117
						Tasks Active: 73
						Tasks Pending: 0
						Tasks Completed: 47044
						Tasks Terminated: 0

WARN
					Metrics after 744 hours:
						Tasks Total: 47117
						Tasks Active: 73
						Tasks Pending: 0
						Tasks Completed: 47044
						Tasks Terminated: 0

WARN
					Metrics after 744 hours:
						Tasks Total: 47117
						Tasks Active: 73
						Tasks Pending: 0
						Tasks Completed: 47044
						Tasks Terminated: 0

Starting replay

WARN
					Metrics after 24 hours:
						Tasks Total: 1172
						Tasks Active: 136
						Tasks Pending: 0
						Tasks Completed: 1036
						Tasks Terminated: 0

WARN
					Metrics after 24 hours:
						Tasks Total: 1172
						Tasks Active: 136
						Tasks Pending: 0
						Tasks Completed: 1036
						Tasks Terminated: 0

WARN
					Metrics after 24 hours:
						Tasks Total: 1172
						Tasks Active: 136
						Tasks Pending: 0
						Tasks Completed: 1036
						Tasks Terminated: 0

WARN
					Metrics after 48 hours:
						Tasks Total: 1413
						Tasks Active: 29
						Tasks Pending: 0
						Tasks Completed: 1384
						Tasks Terminated: 0

WARN
					Metrics after 48 hours:
						Tasks Total: 1413
						Tasks Active: 29
						Tasks Pending: 0
						Tasks Completed: 1384
						Tasks Terminated: 0

WARN
					Metrics after 48 hours:
						Tasks Total: 1413
						Tasks Active: 29
						Tasks Pending: 0
						Tasks Completed: 1384
						Tasks Terminated: 0

WARN
					Metrics after 72 hours:
						Tasks Total: 1608
						Tasks Active: 21
						Tasks Pending: 0
						Tasks Completed: 1587
						Tasks Terminated: 0

WARN
					Metrics after 72 hours:
						Tasks Total: 1608
						Tasks Active: 21
						Tasks Pending: 0
						Tasks Completed: 1587
						Tasks Terminated: 0

WARN
					Metrics after 72 hours:
						Tasks Total: 1608
						Tasks Active: 21
						Tasks Pending: 0
						Tasks Completed: 1587
						Tasks Terminated: 0

WARN
					Metrics after 96 hours:
						Tasks Total: 3087
						Tasks Active: 35
						Tasks Pending: 0
						Tasks Completed: 3052
						Tasks Terminated: 0

WARN
					Metrics after 96 hours:
						Tasks Total: 3087
						Tasks Active: 35
						Tasks Pending: 0
						Tasks Completed: 3052
						Tasks Terminated: 0

WARN
					Metrics after 96 hours:
						Tasks Total: 3087
						Tasks Active: 35
						Tasks Pending: 0
						Tasks Completed: 3052
						Tasks Terminated: 0

WARN
					Metrics after 120 hours:
						Tasks Total: 4613
						Tasks Active: 32
						Tasks Pending: 0
						Tasks Completed: 4581
						Tasks Terminated: 0

WARN
					Metrics after 120 hours:
						Tasks Total: 4613
						Tasks Active: 32
						Tasks Pending: 0
						Tasks Completed: 4581
						Tasks Terminated: 0

WARN
					Metrics after 120 hours:
						Tasks Total: 4613
						Tasks Active: 32
						Tasks Pending: 0
						Tasks Completed: 4581
						Tasks Terminated: 0

WARN
					Metrics after 144 hours:
						Tasks Total: 5491
						Tasks Active: 41
						Tasks Pending: 0
						Tasks Completed: 5450
						Tasks Terminated: 0

WARN
					Metrics after 144 hours:
						Tasks Total: 5491
						Tasks Active: 41
						Tasks Pending: 0
						Tasks Completed: 5450
						Tasks Terminated: 0

WARN
					Metrics after 144 hours:
						Tasks Total: 5491
						Tasks Active: 41
						Tasks Pending: 0
						Tasks Completed: 5450
						Tasks Terminated: 0

WARN
					Metrics after 168 hours:
						Tasks Total: 5969
						Tasks Active: 54
						Tasks Pending: 0
						Tasks Completed: 5915
						Tasks Terminated: 0

WARN
					Metrics after 168 hours:
						Tasks Total: 5969
						Tasks Active: 54
						Tasks Pending: 0
						Tasks Completed: 5915
						Tasks Terminated: 0

WARN
					Metrics after 168 hours:
						Tasks Total: 5969
						Tasks Active: 54
						Tasks Pending: 0
						Tasks Completed: 5915
						Tasks Terminated: 0

WARN
					Metrics after 192 hours:
						Tasks Total: 6794
						Tasks Active: 66
						Tasks Pending: 0
						Tasks Completed: 6728
						Tasks Terminated: 0

WARN
					Metrics after 192 hours:
						Tasks Total: 6794
						Tasks Active: 66
						Tasks Pending: 0
						Tasks Completed: 6728
						Tasks Terminated: 0

WARN
					Metrics after 192 hours:
						Tasks Total: 6794
						Tasks Active: 66
						Tasks Pending: 0
						Tasks Completed: 6728
						Tasks Terminated: 0

WARN
					Metrics after 216 hours:
						Tasks Total: 7314
						Tasks Active: 74
						Tasks Pending: 0
						Tasks Completed: 7240
						Tasks Terminated: 0

WARN
					Metrics after 216 hours:
						Tasks Total: 7314
						Tasks Active: 74
						Tasks Pending: 0
						Tasks Completed: 7240
						Tasks Terminated: 0

WARN
					Metrics after 216 hours:
						Tasks Total: 7314
						Tasks Active: 74
						Tasks Pending: 0
						Tasks Completed: 7240
						Tasks Terminated: 0

WARN
					Metrics after 240 hours:
						Tasks Total: 7977
						Tasks Active: 39
						Tasks Pending: 0
						Tasks Completed: 7938
						Tasks Terminated: 0

WARN
					Metrics after 240 hours:
						Tasks Total: 7977
						Tasks Active: 39
						Tasks Pending: 0
						Tasks Completed: 7938
						Tasks Terminated: 0

WARN
					Metrics after 240 hours:
						Tasks Total: 7977
						Tasks Active: 39
						Tasks Pending: 0
						Tasks Completed: 7938
						Tasks Terminated: 0

WARN
					Metrics after 264 hours:
						Tasks Total: 9618
						Tasks Active: 156
						Tasks Pending: 0
						Tasks Completed: 9462
						Tasks Terminated: 0

WARN
					Metrics after 264 hours:
						Tasks Total: 9618
						Tasks Active: 156
						Tasks Pending: 0
						Tasks Completed: 9462
						Tasks Terminated: 0

WARN
					Metrics after 264 hours:
						Tasks Total: 9618
						Tasks Active: 156
						Tasks Pending: 0
						Tasks Completed: 9462
						Tasks Terminated: 0

WARN
					Metrics after 288 hours:
						Tasks Total: 11069
						Tasks Active: 130
						Tasks Pending: 0
						Tasks Completed: 10939
						Tasks Terminated: 0

WARN
					Metrics after 288 hours:
						Tasks Total: 11069
						Tasks Active: 130
						Tasks Pending: 0
						Tasks Completed: 10939
						Tasks Terminated: 0

WARN
					Metrics after 288 hours:
						Tasks Total: 11069
						Tasks Active: 130
						Tasks Pending: 0
						Tasks Completed: 10939
						Tasks Terminated: 0

WARN
					Metrics after 312 hours:
						Tasks Total: 14997
						Tasks Active: 193
						Tasks Pending: 0
						Tasks Completed: 14804
						Tasks Terminated: 0

WARN
					Metrics after 312 hours:
						Tasks Total: 14997
						Tasks Active: 193
						Tasks Pending: 0
						Tasks Completed: 14804
						Tasks Terminated: 0

WARN
					Metrics after 312 hours:
						Tasks Total: 14997
						Tasks Active: 193
						Tasks Pending: 0
						Tasks Completed: 14804
						Tasks Terminated: 0

WARN
					Metrics after 336 hours:
						Tasks Total: 16752
						Tasks Active: 206
						Tasks Pending: 0
						Tasks Completed: 16546
						Tasks Terminated: 0

WARN
					Metrics after 336 hours:
						Tasks Total: 16752
						Tasks Active: 206
						Tasks Pending: 0
						Tasks Completed: 16546
						Tasks Terminated: 0

WARN
					Metrics after 336 hours:
						Tasks Total: 16752
						Tasks Active: 206
						Tasks Pending: 0
						Tasks Completed: 16546
						Tasks Terminated: 0

WARN
					Metrics after 360 hours:
						Tasks Total: 17933
						Tasks Active: 129
						Tasks Pending: 0
						Tasks Completed: 17804
						Tasks Terminated: 0

WARN
					Metrics after 360 hours:
						Tasks Total: 17933
						Tasks Active: 129
						Tasks Pending: 0
						Tasks Completed: 17804
						Tasks Terminated: 0

WARN
					Metrics after 360 hours:
						Tasks Total: 17933
						Tasks Active: 129
						Tasks Pending: 0
						Tasks Completed: 17804
						Tasks Terminated: 0

WARN
					Metrics after 384 hours:
						Tasks Total: 19072
						Tasks Active: 116
						Tasks Pending: 0
						Tasks Completed: 18956
						Tasks Terminated: 0

WARN
					Metrics after 384 hours:
						Tasks Total: 19072
						Tasks Active: 116
						Tasks Pending: 0
						Tasks Completed: 18956
						Tasks Terminated: 0

WARN
					Metrics after 384 hours:
						Tasks Total: 19072
						Tasks Active: 116
						Tasks Pending: 0
						Tasks Completed: 18956
						Tasks Terminated: 0

WARN
					Metrics after 408 hours:
						Tasks Total: 19427
						Tasks Active: 103
						Tasks Pending: 0
						Tasks Completed: 19324
						Tasks Terminated: 0

WARN
					Metrics after 408 hours:
						Tasks Total: 19427
						Tasks Active: 103
						Tasks Pending: 0
						Tasks Completed: 19324
						Tasks Terminated: 0

WARN
					Metrics after 408 hours:
						Tasks Total: 19427
						Tasks Active: 103
						Tasks Pending: 0
						Tasks Completed: 19324
						Tasks Terminated: 0

WARN
					Metrics after 432 hours:
						Tasks Total: 20937
						Tasks Active: 159
						Tasks Pending: 0
						Tasks Completed: 20778
						Tasks Terminated: 0

WARN
					Metrics after 432 hours:
						Tasks Total: 20937
						Tasks Active: 159
						Tasks Pending: 0
						Tasks Completed: 20778
						Tasks Terminated: 0

WARN
					Metrics after 432 hours:
						Tasks Total: 20937
						Tasks Active: 159
						Tasks Pending: 0
						Tasks Completed: 20778
						Tasks Terminated: 0

WARN
					Metrics after 456 hours:
						Tasks Total: 22387
						Tasks Active: 273
						Tasks Pending: 0
						Tasks Completed: 22114
						Tasks Terminated: 0

WARN
					Metrics after 456 hours:
						Tasks Total: 22387
						Tasks Active: 273
						Tasks Pending: 0
						Tasks Completed: 22114
						Tasks Terminated: 0

WARN
					Metrics after 456 hours:
						Tasks Total: 22387
						Tasks Active: 273
						Tasks Pending: 0
						Tasks Completed: 22114
						Tasks Terminated: 0

WARN
					Metrics after 480 hours:
						Tasks Total: 24301
						Tasks Active: 252
						Tasks Pending: 0
						Tasks Completed: 24049
						Tasks Terminated: 0

WARN
					Metrics after 480 hours:
						Tasks Total: 24301
						Tasks Active: 252
						Tasks Pending: 0
						Tasks Completed: 24049
						Tasks Terminated: 0

WARN
					Metrics after 480 hours:
						Tasks Total: 24301
						Tasks Active: 252
						Tasks Pending: 0
						Tasks Completed: 24049
						Tasks Terminated: 0

WARN
					Metrics after 504 hours:
						Tasks Total: 25880
						Tasks Active: 226
						Tasks Pending: 0
						Tasks Completed: 25654
						Tasks Terminated: 0

WARN
					Metrics after 504 hours:
						Tasks Total: 25880
						Tasks Active: 226
						Tasks Pending: 0
						Tasks Completed: 25654
						Tasks Terminated: 0

WARN
					Metrics after 504 hours:
						Tasks Total: 25880
						Tasks Active: 226
						Tasks Pending: 0
						Tasks Completed: 25654
						Tasks Terminated: 0

WARN
					Metrics after 528 hours:
						Tasks Total: 27270
						Tasks Active: 127
						Tasks Pending: 0
						Tasks Completed: 27143
						Tasks Terminated: 0

WARN
					Metrics after 528 hours:
						Tasks Total: 27270
						Tasks Active: 127
						Tasks Pending: 0
						Tasks Completed: 27143
						Tasks Terminated: 0

WARN
					Metrics after 528 hours:
						Tasks Total: 27270
						Tasks Active: 127
						Tasks Pending: 0
						Tasks Completed: 27143
						Tasks Terminated: 0

WARN
					Metrics after 552 hours:
						Tasks Total: 30122
						Tasks Active: 97
						Tasks Pending: 0
						Tasks Completed: 30025
						Tasks Terminated: 0

WARN
					Metrics after 552 hours:
						Tasks Total: 30122
						Tasks Active: 97
						Tasks Pending: 0
						Tasks Completed: 30025
						Tasks Terminated: 0

WARN
					Metrics after 552 hours:
						Tasks Total: 30122
						Tasks Active: 97
						Tasks Pending: 0
						Tasks Completed: 30025
						Tasks Terminated: 0

WARN
					Metrics after 576 hours:
						Tasks Total: 30674
						Tasks Active: 98
						Tasks Pending: 0
						Tasks Completed: 30576
						Tasks Terminated: 0

WARN
					Metrics after 576 hours:
						Tasks Total: 30674
						Tasks Active: 98
						Tasks Pending: 0
						Tasks Completed: 30576
						Tasks Terminated: 0

WARN
					Metrics after 576 hours:
						Tasks Total: 30674
						Tasks Active: 98
						Tasks Pending: 0
						Tasks Completed: 30576
						Tasks Terminated: 0

WARN
					Metrics after 600 hours:
						Tasks Total: 33314
						Tasks Active: 150
						Tasks Pending: 0
						Tasks Completed: 33164
						Tasks Terminated: 0

WARN
					Metrics after 600 hours:
						Tasks Total: 33314
						Tasks Active: 150
						Tasks Pending: 0
						Tasks Completed: 33164
						Tasks Terminated: 0

WARN
					Metrics after 600 hours:
						Tasks Total: 33314
						Tasks Active: 150
						Tasks Pending: 0
						Tasks Completed: 33164
						Tasks Terminated: 0

WARN
					Metrics after 624 hours:
						Tasks Total: 35894
						Tasks Active: 163
						Tasks Pending: 0
						Tasks Completed: 35731
						Tasks Terminated: 0

WARN
					Metrics after 624 hours:
						Tasks Total: 35894
						Tasks Active: 163
						Tasks Pending: 0
						Tasks Completed: 35731
						Tasks Terminated: 0

WARN
					Metrics after 624 hours:
						Tasks Total: 35894
						Tasks Active: 163
						Tasks Pending: 0
						Tasks Completed: 35731
						Tasks Terminated: 0

WARN
					Metrics after 648 hours:
						Tasks Total: 39943
						Tasks Active: 253
						Tasks Pending: 0
						Tasks Completed: 39690
						Tasks Terminated: 0

WARN
					Metrics after 648 hours:
						Tasks Total: 39943
						Tasks Active: 253
						Tasks Pending: 0
						Tasks Completed: 39690
						Tasks Terminated: 0

WARN
					Metrics after 648 hours:
						Tasks Total: 39943
						Tasks Active: 253
						Tasks Pending: 0
						Tasks Completed: 39690
						Tasks Terminated: 0

WARN
					Metrics after 672 hours:
						Tasks Total: 42909
						Tasks Active: 114
						Tasks Pending: 0
						Tasks Completed: 42795
						Tasks Terminated: 0

WARN
					Metrics after 672 hours:
						Tasks Total: 42909
						Tasks Active: 114
						Tasks Pending: 0
						Tasks Completed: 42795
						Tasks Terminated: 0

WARN
					Metrics after 672 hours:
						Tasks Total: 42909
						Tasks Active: 114
						Tasks Pending: 0
						Tasks Completed: 42795
						Tasks Terminated: 0

WARN
					Metrics after 696 hours:
						Tasks Total: 46868
						Tasks Active: 111
						Tasks Pending: 0
						Tasks Completed: 46757
						Tasks Terminated: 0

WARN
					Metrics after 696 hours:
						Tasks Total: 46868
						Tasks Active: 111
						Tasks Pending: 0
						Tasks Completed: 46757
						Tasks Terminated: 0

WARN
					Metrics after 696 hours:
						Tasks Total: 46868
						Tasks Active: 111
						Tasks Pending: 0
						Tasks Completed: 46757
						Tasks Terminated: 0

WARN
					Metrics after 720 hours:
						Tasks Total: 47022
						Tasks Active: 79
						Tasks Pending: 0
						Tasks Completed: 46943
						Tasks Terminated: 0

WARN
					Metrics after 720 hours:
						Tasks Total: 47022
						Tasks Active: 79
						Tasks Pending: 0
						Tasks Completed: 46943
						Tasks Terminated: 0

WARN
					Metrics after 720 hours:
						Tasks Total: 47022
						Tasks Active: 79
						Tasks Pending: 0
						Tasks Completed: 46943
						Tasks Terminated: 0

WARN
					Metrics after 744 hours:
						Tasks Total: 47117
						Tasks Active: 73
						Tasks Pending: 0
						Tasks Completed: 47044
						Tasks Terminated: 0

WARN
					Metrics after 744 hours:
						Tasks Total: 47117
						Tasks Active: 73
						Tasks Pending: 0
						Tasks Completed: 47044
						Tasks Terminated: 0

WARN
					Metrics after 744 hours:
						Tasks Total: 47117
						Tasks Active: 73
						Tasks Pending: 0
						Tasks Completed: 47044
						Tasks Terminated: 0

┌─────────┬──────┬──────┬──────────┬──────────┬────────┬───────────┬──────────┐
│ Scenario│ Seed │ Tasks│ Completed│ Terminate│ Mean CP│ Energy [kW│ Carbon [k│
├─────────┼──────┼──────┼──────────┼──────────┼────────┼───────────┼──────────┤
│ #0      │ 0    │ 47117│ 47117    │ 0        │ 18.8%  │ 4612293.35│ 1573769.6│
├─────────┼──────┼──────┼──────────┼──────────┼────────┼───────────┼──────────┤
│ #1      │ 0    │ 47117│ 47117    │ 0        │ 18.8%  │ 4635982.34│ 1344123.4│
├─────────┼──────┼──────┼──────────┼──────────┼────────┼───────────┼──────────┤
│ #2      │ 0    │ 47117│ 47117    │ 0        │ 18.8%  │ 4680617.02│ 1185616.4│
├─────────┼──────┼──────┼──────────┼──────────┼────────┼───────────┼──────────┤
│ #3      │ 0    │ 47117│ 47117    │ 0        │ 18.8%  │ 4741725.69│ 1139449.1│
├─────────┼──────┼──────┼──────────┼──────────┼────────┼───────────┼──────────┤
│ #4      │ 0    │ 47117│ 47117    │ 0        │ 18.8%  │ 4810819.79��� 1148614.5│
└─────────┴──────┴──────┴──────────┴──────────┴────────┴───────────┴──────────┘
Simulated 5 run(s); Parquet results in output

## 6. Output

In [29]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


df_host_no = pd.read_parquet("output/4.batteries/raw-output/0/seed=0/host.parquet")
df_powerSource_no = pd.read_parquet("output/4.batteries/raw-output/0/seed=0/powerSource.parquet")
df_task_no = pd.read_parquet("output/4.batteries/raw-output/0/seed=0/task.parquet")
df_service_no = pd.read_parquet("output/4.batteries/raw-output/0/seed=0/service.parquet")
df_battery_no = pd.read_parquet("output/4.batteries/raw-output/0/seed=0/battery.parquet")

df_host_100 = pd.read_parquet("output/4.batteries/raw-output/1/seed=0/host.parquet")
df_powerSource_100 = pd.read_parquet("output/4.batteries/raw-output/1/seed=0/powerSource.parquet")
df_task_100 = pd.read_parquet("output/4.batteries/raw-output/1/seed=0/task.parquet")
df_service_100 = pd.read_parquet("output/4.batteries/raw-output/1/seed=0/service.parquet")
df_battery_100 = pd.read_parquet("output/4.batteries/raw-output/1/seed=0/battery.parquet")

df_host_200 = pd.read_parquet("output/4.batteries/raw-output/2/seed=0/host.parquet")
df_powerSource_200 = pd.read_parquet("output/4.batteries/raw-output/2/seed=0/powerSource.parquet")
df_task_200 = pd.read_parquet("output/4.batteries/raw-output/2/seed=0/task.parquet")
df_service_200 = pd.read_parquet("output/4.batteries/raw-output/2/seed=0/service.parquet")
df_battery_200 = pd.read_parquet("output/4.batteries/raw-output/2/seed=0/battery.parquet")

df_host_300 = pd.read_parquet("output/4.batteries/raw-output/3/seed=0/host.parquet")
df_powerSource_300 = pd.read_parquet("output/4.batteries/raw-output/3/seed=0/powerSource.parquet")
df_task_300 = pd.read_parquet("output/4.batteries/raw-output/3/seed=0/task.parquet")
df_service_300 = pd.read_parquet("output/4.batteries/raw-output/3/seed=0/service.parquet")
df_battery_300 = pd.read_parquet("output/4.batteries/raw-output/3/seed=0/battery.parquet")

df_host_400 = pd.read_parquet("output/4.batteries/raw-output/4/seed=0/host.parquet")
df_powerSource_400 = pd.read_parquet("output/4.batteries/raw-output/4/seed=0/powerSource.parquet")
df_task_400 = pd.read_parquet("output/4.batteries/raw-output/4/seed=0/task.parquet")
df_service_400 = pd.read_parquet("output/4.batteries/raw-output/4/seed=0/service.parquet")
df_battery_400 = pd.read_parquet("output/4.batteries/raw-output/4/seed=0/battery.parquet")

In [30]:
print(f"Operational carbon for no battery:      {df_powerSource_no['carbon_emission'].max() / 1_000:.2f} kg")
print(f"Operational carbon for 100 kWh battery: {df_powerSource_100['carbon_emission'].max() / 1_000:.2f} kg")
print(f"Operational carbon for 200 kWh battery: {df_powerSource_200['carbon_emission'].max() / 1_000:.2f} kg")
print(f"Operational carbon for 300 kWh battery: {df_powerSource_300['carbon_emission'].max() / 1_000:.2f} kg")
print(f"Operational carbon for 400 kWh battery: {df_powerSource_400['carbon_emission'].max() / 1_000:.2f} kg\n")

print(f"embodied carbon for no battery:      {0} kg")
print(f"embodied carbon for 100 kWh battery: {df_battery_100['embodied_carbon_emission'].max() / 1_000:.2f} kg")
print(f"embodied carbon for 200 kWh battery: {df_battery_200['embodied_carbon_emission'].max() / 1_000:.2f} kg")
print(f"embodied carbon for 300 kWh battery: {df_battery_300['embodied_carbon_emission'].max() / 1_000:.2f} kg")
print(f"embodied carbon for 400 kWh battery: {df_battery_400['embodied_carbon_emission'].max() / 1_000:.2f} kg\n")

total_carbon_no = df_powerSource_no['carbon_emission'].max() / 1_000
total_carbon_100 = (df_powerSource_100['carbon_emission'].max()+ df_battery_100['embodied_carbon_emission'].max()) / 1_000
total_carbon_200 = (df_powerSource_200['carbon_emission'].max()+ df_battery_200['embodied_carbon_emission'].max()) / 1_000
total_carbon_300 = (df_powerSource_300['carbon_emission'].max()+ df_battery_300['embodied_carbon_emission'].max()) / 1_000
total_carbon_400 = (df_powerSource_400['carbon_emission'].max()+ df_battery_400['embodied_carbon_emission'].max()) / 1_000

print(f"Total carbon for no battery:      {total_carbon_no:.2f} kg")
print(f"Total carbon for 100 kWh battery: {total_carbon_100:.2f} kg")
print(f"Total carbon for 200 kWh battery: {total_carbon_200:.2f} kg")
print(f"Total carbon for 300 kWh battery: {total_carbon_300:.2f} kg ")
print(f"Total carbon for 400 kWh battery: {total_carbon_400:.2f} kg\n")

Operational carbon for no battery:      4856.71 kg
Operational carbon for 100 kWh battery: 4233.76 kg
Operational carbon for 200 kWh battery: 3719.39 kg
Operational carbon for 300 kWh battery: 3485.97 kg
Operational carbon for 400 kWh battery: 3423.82 kg

embodied carbon for no battery:      0 kg
embodied carbon for 100 kWh battery: 84.93 kg
embodied carbon for 200 kWh battery: 169.86 kg
embodied carbon for 300 kWh battery: 254.79 kg
embodied carbon for 400 kWh battery: 339.73 kg

Total carbon for no battery:      4856.71 kg
Total carbon for 100 kWh battery: 4318.69 kg
Total carbon for 200 kWh battery: 3889.26 kg
Total carbon for 300 kWh battery: 3740.76 kg
Total carbon for 400 kWh battery: 3763.55 kg

In [24]:
df_battery_100

,timestamp,battery_id,power_draw,energy_usage,embodied_carbon_emission,charge,battery_state
0,3600000,0,0.0,0.000000e+00,114.155251,0.0,IDLE
1,7200000,0,0.0,0.000000e+00,228.310501,0.0,IDLE
2,10800000,0,0.0,0.000000e+00,342.465759,0.0,IDLE
3,14400000,0,0.0,0.000000e+00,456.621002,0.0,IDLE
4,18000000,0,0.0,0.000000e+00,570.776245,0.0,IDLE
...,...,...,...,...,...,...,...
740,2667600000,0,0.0,1.107226e+10,84589.039062,12000000.0,CHARGING
741,2671200000,0,0.0,1.107226e+10,84703.195312,360000096.0,IDLE
742,2674800000,0,0.0,1.107226e+10,84817.351562,360000096.0,IDLE
743,2678400000,0,0.0,1.107226e+10,84931.507812,360000096.0,IDLE
744,2678400000,0,0.0,1.107226e+10,84931.507812,360000096.0,IDLE